Vagrant.configure("2") do |c|
  c.vm.define 'ubuntu-14-04' do |v|
    v.vm.hostname = 'ubuntu-14-04'
    v.vm.box = 'puppetlabs/ubuntu-14.04-64-puppet'
    v.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet'
    v.vm.box_check_update = 'true'
    v.vm.base_mac = '0800271B6EC7'
    v.vm.network :private_network, ip: "10.255.37.94", :netmask => "255.255.0.0"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
  end
end
